[project]
name = "genomic-sparse-attention"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.3.0",
    "numpy>=1.20.0",
    "seaborn>=0.11.0",
    "torch>=2.0.0",
]
